language: python

python:
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install coverage

install:
  - pip install -r requirements.txt

script:
  - python bcselector/run_tests.py
  - coverage run bcselector/run_tests.py

after_success:
  - coverage